version: '3.9'
services:
  server:
    image: server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app:/log/app
    environment:
      - DB_ADDR=redis:6379
      - TIKTOK_USERNAME=<USERNAME>
      - TG_TOKEN=<TG_TOKEN>
      - CHANNEL_ID=<ID>
    depends_on:
      - redis
  redis:
    image: "redis:7.0.5-alpine"
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    restart: always
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
  app:
    driver: local
